@startuml
'!pragma layout smetana
'https://plantuml.com/class-diagram

scale 0.9

abstract class Parent1
Parent1 <|--- Subclass    : <<is-a>>\n\ninherits\n (extends)

interface Parent2
Parent2 <|... Class2      : <<is-a>>\n\nrealizes\n (implements)

Whole1  *---  PartClass1  : <<has-a>>\n\nis compo-\nsed of

Whole2  o---  PartClass2  : <<has-a>>\n\naggregates

ClassA  <...  ClassB      : <<call>>\n\nuses

ClassC  <---  ClassD      : "     "
ClassC  ---  ClassD       : <<?>>\nis asso-\nciated with\n(//mit/ohne//\n//"Richtung"//)

@enduml