include::../../docs/settings.adoc[]
:author: Thorsten Eckstein

:toc:


== Klassen & Objekte (Instanzen)

Die wichtigsten Elemente von Java:

[source,java]
----
- interface
- (abstract) class
- field
- method
----

Erzeuge ein erstes, kleines *Klassenmodell*:

- Ein Interface `Train` mit mit zugehörigen Methoden für ein Attribut namens `train number`
- Eine Klasse `EuroExpress`, die das Interface `Train` implementiert, also auch das erforderliche Attribut beinhaltet
- Ebenso eine weitere Klasse `Intercity`, die das Interface `Train` implementiert
- Einen Test, der je eine Instanz der zwei Implementierungen erzeugt und deren Zugnummer ausgibt

 Frage   : Was fällt bei der Implementierung jetzt besonders ins Auge?
 Antwort : ?



////
Das Interface `Train` sieht dabei vielleicht so aus:

[source, java, linenums]
----
include::{course-1-src}/model/train/Train.java[lines=5..13]
----
////



== Statische Klassen und Variablen mit static

Das Schlüsselwort

 static

bedeutet im Wesentlichen, das die Felder (Attribute) oder Methoden einer Klasse nicht an die Erzeugung einer *Instanz* dieser Klasse gebunden sind. Das Ganze lässt sich besser anhand von Beispielen und Code verdeutlichen.

Ein Beispiel:

[source, java]
----
public class Configuration {

    public static final String SETTING_KEY_AUTHOR = "setting.author";

    public static String getSetting(String key) {
        return settings.get(key);
    }

}
----

Dazu gibt es auch *Unit-Tests*:

// Note: class reference can be easily determined using "path from content root"
[subs=attributes]
 src/test/java/de/dhbw/StaticsDemoTest.java


== Vererbung & Implementierung mit Interfaces


// == Abstrakte Klassen


// == Sichtbarkeiten & Scopes: Access Modifier


// == Quellcodeverwaltung mit Git


// == Dependency-Management mit Maven (pom)