include::../../docs/settings.adoc[]
include::module-settings.adoc[]
:author: Thorsten Eckstein

:toc:


== Klassen & Objekte (Instanzen)

[ <<about_classes,Inhalt>> | <<demos_classes,Demo>> | <<exercises_classes,Übungen>> ]

[[about_classes]]
Kurz etwas *Theorie* vorab bzw. zur Wiederholung:

Unter einer *Klasse* (oder Objekttyp, -> <<ref-1,Ref. 1>>) versteht man in der objektorientierten Programmierung ein abstraktes Modell bzw. einen Bauplan für eine Reihe von ähnlichen Objekten.

Die Klasse dient als Bauplan für die Abbildung von realen Objekten in Softwareobjekte und beschreibt Attribute (Eigenschaften, Felder) und Methoden (Verhaltensweisen) der Objekte. Etwas allgemeiner kann auch gesagt werden, dass eine Klasse dem *Datentyp eines Objekts* entspricht.

Eine Java Klasse hat in der Regel folgende Bestandteile:

* Eigenschaft (Feld),
* Konstruktor und
* Verhaltensweise (Methode):

Die *Klassensignatur* selbst:

[source,java]
----
public class MyClass {

}
----

Eine Klasse mit einem *Feld* bzw. einer Eigenschaft:

[source,java]
----
public class MyClass {

    public String field;

}
----

Eine Klasse mit (Default-) *Konstruktor*:

[source,java]
----
public class MyClass {

    public MyClass() {

    }

}
----

Eine Klasse mit einer *Methode* bzw. einer Verhaltensweise:

[source,java]
----
public class MyClass {

    public String doSomething() {
        return "result";
    }

}
----


[[demos_classes]]
*Demo*:

[subs=normal]
 -> {module-ref-tests}/ClassesDemoTest.java


[[exercises_classes]]
*Übungen*:



Erzeuge ein erstes, kleines *Klassenmodell*:

- Ein Interface `Train` mit mit zugehörigen Methoden für ein Attribut namens `train number`
- Eine Klasse `EuroExpress`, die das Interface `Train` implementiert, also auch das erforderliche Attribut beinhaltet
- Ebenso eine weitere Klasse `Intercity`, die das Interface `Train` implementiert
- Einen Test, der je eine Instanz der zwei Implementierungen erzeugt und deren Zugnummer ausgibt

 Frage   : Was fällt bei der Implementierung jetzt besonders ins Auge?
 Antwort : ?



////
Das Interface `Train` sieht dabei vielleicht so aus:

[source, java, linenums]
----
include::{course-1-src}/model/train/Train.java[lines=5..13]
----
////



== Statische Klassen und Variablen mit static

Das Schlüsselwort

 static

bedeutet im Wesentlichen, das die Felder (Attribute) oder Methoden einer Klasse nicht an die Erzeugung einer *Instanz* dieser Klasse gebunden sind. Das Ganze lässt sich besser anhand von Beispielen und Code verdeutlichen.

Ein *Beispiel*:

[source, java]
----
public class Configuration {

    // statisches Feld
    public static final String SETTING_KEY_AUTHOR = "setting.author";

    // statische Methode
    public static String getSetting(String key) {
        return settings.get(key);
    }

}
----

Dazu gibt es auch *Unit-Tests*:

// Note: class reference can be easily determined using "path from content root"
[subs=attributes]
 src/test/java/de/dhbw/StaticsDemoTest.java


== Vererbung & Implementierung mit Interfaces


== Referenzen

[[ref-1]]
Ref. 1: https://de.wikipedia.org/wiki/Klasse_(Objektorientierung)[https://de.wikipedia.org/wiki/Klasse_(Objektorientierung)]


// == Abstrakte Klassen


// == Sichtbarkeiten & Scopes: Access Modifier


