@startuml
'https://plantuml.com/class-diagram

scale 1.0

class LV   as "Lehrveranstaltung (LV)"
class TdLV as "        Tag der LV            "
class Mod  as "           Modul                "

'LV     "1"   *--   "1..n"    TdLV
'TdLV   "1"   *--   "1..n"    Mod

LV     "1"   *--   "1..n"    Mod
Mod          --              TdLV

@enduml