@startuml
'https://plantuml.com/class-diagram

skinparam groupInheritance 1

scale 0.8

class "Imperative\nProgrammierung" as IP
class "Prozedurale\nProgrammierung" as PP
class "Objektorientierte\nProgrammierung" as OOP

class "Deklarative\nProgrammierung" as DP
class "Funktionale\nProgrammierung" as FP
class "Logische\nProgrammierung" as LP

IP <|-- PP
IP <|-- OOP

DP <|-- FP
DP <|-- LP

@enduml