include::../../docs/settings.adoc[]
include::module-settings.adoc[]
:author: Thorsten Eckstein

// table of contents
:toc:


// Set 'show-structure' in settings.adoc to 'true' to display explicitly here
ifeval::[{show-structure} == true]
include::planning.adoc[]
endif::[]


== Sichtbarkeiten & Scopes: Access Modifier

[ <<about_scopes,Inhalt>> | <<demos_scopes,Demo>> | <<exercises_scopes,Übungen>> ]

[[about_scopes]]
Die Standard *Access Modifier* sind `default`, `public`, `protected` sowie `private`. Sie bedeuten:

`default`::

Wenn kein Schlüsselwort explizit verwendet wird, legt Java einen Standardzugriff auf eine bestimmte Klasse, Methode oder Eigenschaft fest. Der *Standardzugriffs*-Modifikator wird auch `package-private` genannt, was bedeutet, dass alle Mitglieder innerhalb desselben Pakets sichtbar sind, aber von anderen Paketen aus nicht darauf zugegriffen werden kann:

`public`::

Wenn einer Klasse, Methode oder Eigenschaft das Schlüsselwort `public` hinzufügt wird, wird es auf der "ganzen Welt" verfügbar/sichtbar, d.h. alle anderen Klassen in allen Paketen können es verwenden. Dies ist der am wenigsten restriktive Zugriffsmodifikator.

`protected`::

Wenn eine Methode, Eigenschaft oder einen Konstruktor mit dem Schlüsselwort `protected` deklariert wird, kann auf das Mitglied aus demselben Paket zugegriffen werden (wie bei der Zugriffsebene Paket-Private) und zusätzlich aus allen Unterklassen dieser Klasse, auch wenn diese in anderen Paketen liegen.

`private`::

Auf jede Methode, Eigenschaft oder jeden Konstruktor mit dem Schlüsselwort `private` kann nur von derselben Klasse, also von "innen", aus zugegriffen werden. Dies ist der restriktivste Zugriffsmodifikator und bildet den Kern des Konzepts der Kapselung. Alle Daten werden vor der Außenwelt verborgen.


[[demos_scopes]]
*Demo:*

[subs=normal]
 -> {mod-ref-test}/demo/VisibilityDemoTest.java

[source,java]
----
include::{mod-lnk-test}/demo/VisibilityDemoTest.java[tags="visibility"]
----

[[exercises_scopes]]
*Übungen*:

[subs=normal]
 -> {mod-ref-test}/exercise/VisibilityExerciseTest.java

Übung 1::

to be specified 


